plugins {
    id 'com.android.application'
}

android {
    namespace 'com.keldurn.browser'
    compileSdk 34

    defaultConfig {
        applicationId "com.keldurn.browser"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
        debug {
            minifyEnabled false
            shrinkResources false
        }
    }

    // FUERZA AL COMPILADOR A APUNTAR A LA CARPETA MAIN
    sourceSets {
        main {
            java.srcDirs = ['src/main/java']
            res.srcDirs = ['src/main/res']
            manifest.srcFile 'src/main/AndroidManifest.xml'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
