plugins {
    id 'com.android.application'
}

android {
    namespace 'com.keldurn.browser'
    compileSdk 34

    defaultConfig {
        applicationId "com.keldurn.browser"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            // Desactiva el encogido y optimización que vacía el APK
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            // Asegura que la versión debug tampoco borre recursos
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
