plugins {
    id 'com.android.application'
}

android {
    namespace 'com.keldurn.browser'
    compileSdk 34

    defaultConfig {
        applicationId "com.keldurn.browser"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
        debug {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

// AGREGA ESTO AL FINAL DEL ARCHIVO
dependencies {
    implementation 'androidx.browser:browser:1.8.0'
}
