name: Empaquetar Clon Frontend Optimizado

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v4

      - name: Estructurar Carpetas y Arquitectura Móvil
        run: |
          echo "Organizando archivos dentro del servidor de GitHub..."
          mkdir -p mobile
          [ -f app.js ] && mv app.js mobile/app.js || true
          [ -f platform.js ] && mv platform.js mobile/platform.js || true
          echo "Estructura de carpetas completada."

      - name: Preparar zona de empaquetado seguro
        run: |
          mkdir -p binario_zip
          # Copiamos absolutamente todo a una carpeta temporal limpia, excepto el pesado .wasm
          rsync -av --exclude='keldurn_bg.wasm' --exclude='.git' --exclude='.github' ./ binario_zip/

      - name: Generar Paquete ZIP de Descarga 📦
        uses: actions/upload-artifact@v4
        with:
          name: Keldurn_Frontend_Modificado
          path: binario_zip/
          retention-days: 1 # Fuerza a GitHub a activar el almacenamiento inmediato del ZIP
          if-no-files-found: error
